/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package add_medicine;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class add_medicine extends javax.swing.JFrame {
   public String numpattern="^[0-9]*$";
   public boolean flage=true;
   
    Connection  con;
    public add_medicine() {
        
        initComponents();
        this.setLocationRelativeTo(null);
       try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "abdo", "abdo1234");
       } 
       catch (SQLException ex) {
           Logger.getLogger(add_medicine.class.getName()).log(Level.SEVERE, null, ex);
       }
              
         save.setBackground(Color.WHITE);
        save.setForeground(new Color(56,78,220)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        m_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        m_name = new javax.swing.JTextField();
        m_company = new javax.swing.JTextField();
        m_quantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        m_price = new javax.swing.JTextField();
        save = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(247, 249, 250));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 78, 220));
        jLabel1.setText("Add Medicine");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 7, 252, -1));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 844, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 78, 220));
        jLabel2.setText("Medicin ID");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 115, -1, 19));

        m_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_idActionPerformed(evt);
            }
        });
        jPanel5.add(m_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 143, 280, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(56, 78, 220));
        jLabel6.setText("Name");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 202, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(56, 78, 220));
        jLabel7.setText("Company Name");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(56, 78, 220));
        jLabel8.setText("Quantity");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 202, -1, -1));

        m_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nameActionPerformed(evt);
            }
        });
        jPanel5.add(m_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 233, 280, 30));

        m_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_companyActionPerformed(evt);
            }
        });
        jPanel5.add(m_company, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 280, 30));

        m_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_quantityActionPerformed(evt);
            }
        });
        jPanel5.add(m_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 233, 280, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(56, 78, 220));
        jLabel9.setText("Price per Unit");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 112, -1, -1));

        m_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_priceActionPerformed(evt);
            }
        });
        jPanel5.add(m_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 143, 280, 30));

        save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(56, 78, 220));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image2/save.png"))); // NOI18N
        save.setText("save");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel5.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 110, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Close Window.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_idActionPerformed

    private void m_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_nameActionPerformed

    private void m_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_quantityActionPerformed

    private void m_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_priceActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        
       try {
           String mid=m_id.getText();
           String mname=m_name.getText();
           String mcompanyname=m_company.getText();
           String mquantity=m_quantity.getText();
           String mprice=m_price.getText();
       
                boolean flage1=true;
                boolean flage2=true;
                boolean flage3=true;
                boolean flage4=true;
                boolean flage5=true;
                boolean flage6=true;
                boolean flage7=true;
                boolean flage8=true;

            if(mid.equals(""))
            {
                JOptionPane.showMessageDialog(null,"medicine ID is required.");
                flage1=false;

            }
            else if(mname.equals(""))
            {
                JOptionPane.showMessageDialog(null,"medicine name is required.");
                flage2=false;

            }
            else if(mquantity.equals(""))
            {
                JOptionPane.showMessageDialog(null,"medicine Quantity is required.");
                flage3=false;

            }
            else if(mprice.equals(""))
            {
                JOptionPane.showMessageDialog(null,"medicine price is required.");
                flage4=false;

            }
            else if(mname.matches(numpattern))
            {
                JOptionPane.showMessageDialog(null, "medicine name is invailed");
                flage5=false;

            }
            else if(mcompanyname.matches(numpattern))
            {
                JOptionPane.showMessageDialog(null, "medicine company is invailed");
                flage6=false;


            }
            else if(!mquantity.matches(numpattern) || mquantity.charAt(0)=='0')
            {
                JOptionPane.showMessageDialog(null, "medicine Quantity is invailed");
                flage7=false;

            }
              else if(!mid.matches(numpattern) || mid.charAt(0)=='0')
            {
                JOptionPane.showMessageDialog(null, "medicine ID is invailed");
                flage7=false;

            }
            else if(!mprice.matches(numpattern) || mprice.charAt(0)=='0')
            {
                JOptionPane.showMessageDialog(null, "medicine price is invailed");
                flage8=false;

            }
          
          
          if(flage1==true&&flage2==true&&flage3==true&&flage4==true&&flage5==true&&flage6==true&&flage7==true&&flage8==true)
          {
           PreparedStatement ps=con.prepareStatement("insert into medicine(uniqueId,name,companyName,quantity,price)VALUES(?,?,?,?,?)");
           ps.setString(1, mid);
           ps.setString(2, mname);
           ps.setString(3, mcompanyname);
           ps.setString(4, mquantity);
           ps.setString(5, mprice);
           ps.executeUpdate();  
           JOptionPane.showMessageDialog(null," Added medicine Successfully.");
          
           setVisible(false);
          }
       } 
       catch (SQLException ex) {
           Logger.getLogger(add_medicine.class.getName()).log(Level.SEVERE, null, ex);
       }
          

    }//GEN-LAST:event_saveActionPerformed

    private void m_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_companyActionPerformed

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        // TODO add your handling code here:
          save.setBackground(new Color(56,78,220));
        save.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image2\\save.png");
    save.setIcon(icon);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        // TODO add your handling code here:
          save.setBackground(Color.WHITE);
        save.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image2\\save.png");
    save.setIcon(icon);

    }//GEN-LAST:event_saveMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField m_company;
    private javax.swing.JTextField m_id;
    private javax.swing.JTextField m_name;
    private javax.swing.JTextField m_price;
    private javax.swing.JTextField m_quantity;
    private javax.swing.JToggleButton save;
    // End of variables declaration//GEN-END:variables
}
