/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pharmacy.management.system.Profile;
import pharmacy.management.system.user;
import pharmacy.management.system.viewuser;
/**
 *
 * @author win10
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     * @param user_name
     */
    public String username;
    public dashboard(String user_name) {
        initComponents();
       username=user_name;
         name_label.setText("Welcome Back, "+user_name);
        this.setTitle("Home page");
        this.setLocation(75, 25);
        this.setSize(1366, 800);
        this.setVisible(true);
             profile.setBackground(Color.WHITE);
        profile.setForeground(new Color(56,78,220));
         addmed.setBackground(Color.WHITE);
        addmed.setForeground(new Color(56,78,220));
          logout_button.setBackground(Color.WHITE);
        logout_button.setForeground(new Color(56,78,220));
         exit_button.setBackground(Color.WHITE);
        exit_button.setForeground(new Color(56,78,220));
         updatemed.setBackground(Color.WHITE);
        updatemed.setForeground(new Color(56,78,220));
            viewmed.setBackground(Color.WHITE);
        viewmed.setForeground(new Color(56,78,220));
          sellmed.setBackground(Color.WHITE);
        sellmed.setForeground(new Color(56,78,220));
         viewbill.setBackground(Color.WHITE);
        viewbill.setForeground(new Color(56,78,220));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        addmed = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        viewmed = new javax.swing.JButton();
        updatemed = new javax.swing.JButton();
        viewbill = new javax.swing.JButton();
        sellmed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 70, 1370, 10);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(570, 10, 270, 58);

        name_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name_label.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.add(name_label);
        name_label.setBounds(40, 30, 470, 40);

        addmed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addmed.setForeground(new java.awt.Color(51, 51, 255));
        addmed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image3/buy-online.png"))); // NOI18N
        addmed.setText("Add Medicine");
        addmed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addmedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addmedMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addmedMousePressed(evt);
            }
        });
        addmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmedActionPerformed(evt);
            }
        });
        jPanel1.add(addmed);
        addmed.setBounds(240, 100, 380, 140);

        profile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        profile.setForeground(new java.awt.Color(51, 51, 255));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user (2).png"))); // NOI18N
        profile.setText("Profile");
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.setFocusable(false);
        profile.setMaximumSize(new java.awt.Dimension(241, 135));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileMousePressed(evt);
            }
        });
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jPanel1.add(profile);
        profile.setBounds(780, 430, 380, 140);

        logout_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout_button.setForeground(new java.awt.Color(51, 51, 255));
        logout_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout (1) (1).png"))); // NOI18N
        logout_button.setText("Log out");
        logout_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_button.setFocusable(false);
        logout_button.setIconTextGap(12);
        logout_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_buttonMouseExited(evt);
            }
        });
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(logout_button);
        logout_button.setBounds(240, 600, 380, 140);

        exit_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exit_button.setForeground(new java.awt.Color(51, 51, 255));
        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/switch.png"))); // NOI18N
        exit_button.setText("Exit");
        exit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_button.setFocusable(false);
        exit_button.setIconTextGap(12);
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_buttonMouseExited(evt);
            }
        });
        jPanel1.add(exit_button);
        exit_button.setBounds(780, 600, 380, 140);

        viewmed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewmed.setForeground(new java.awt.Color(51, 51, 255));
        viewmed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image3/list.png"))); // NOI18N
        viewmed.setText("View Medicine");
        viewmed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewmed.setFocusable(false);
        viewmed.setIconTextGap(12);
        viewmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewmedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewmedMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewmedMousePressed(evt);
            }
        });
        viewmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmedActionPerformed(evt);
            }
        });
        jPanel1.add(viewmed);
        viewmed.setBounds(240, 260, 380, 140);

        updatemed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updatemed.setForeground(new java.awt.Color(51, 51, 255));
        updatemed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image3/edit.png"))); // NOI18N
        updatemed.setText("Update Medicine");
        updatemed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatemed.setFocusable(false);
        updatemed.setIconTextGap(12);
        updatemed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatemedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatemedMouseExited(evt);
            }
        });
        updatemed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemedActionPerformed(evt);
            }
        });
        jPanel1.add(updatemed);
        updatemed.setBounds(240, 430, 380, 140);

        viewbill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewbill.setForeground(new java.awt.Color(51, 51, 255));
        viewbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image3/prescription.png"))); // NOI18N
        viewbill.setText("View Bill");
        viewbill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewbill.setFocusable(false);
        viewbill.setIconTextGap(12);
        viewbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewbillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewbillMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewbillMousePressed(evt);
            }
        });
        viewbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbillActionPerformed(evt);
            }
        });
        jPanel1.add(viewbill);
        viewbill.setBounds(780, 260, 380, 140);

        sellmed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sellmed.setForeground(new java.awt.Color(51, 51, 255));
        sellmed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image3/medication (1).png"))); // NOI18N
        sellmed.setText("Sell Medicine");
        sellmed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sellmed.setFocusable(false);
        sellmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellmedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sellmedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sellmedMouseExited(evt);
            }
        });
        sellmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellmedActionPerformed(evt);
            }
        });
        jPanel1.add(sellmed);
        sellmed.setBounds(780, 100, 380, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseExited
        // TODO add your handling code here:
        profile.setBackground(Color.WHITE);
        profile.setForeground(new Color(56,78,220));
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image\\user (2).png");
        profile.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (profile.getWidth() -25);  // Increase width by 20%
        int newHeight = (int) (profile.getHeight() -25);  // Increase height by 20%

        // Set the bounds for the button manually
        profile.setBounds(profile.getX()+10, profile.getY()+10, newWidth, newHeight);

    }//GEN-LAST:event_profileMouseExited

    private void profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseEntered
        // TODO add your handling code here:
        profile.setBackground(new Color(56,78,220));
        profile.setForeground(Color.WHITE);
        // Set icon for the button
        ImageIcon icon = new ImageIcon("C:\\Users\\win10\\Documents\\NetBeansProjects\\pharmacyMS\\src\\image\\profile.png");
        profile.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (profile.getWidth() +25);  // Increase width by 20%
        int newHeight = (int) (profile.getHeight() +25);  // Increase height by 20%

        // Set the bounds for the button manually
        profile.setBounds(profile.getX()-10, profile.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_profileMouseEntered

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        new Profile(username).setVisible(true);//dispose();
    }//GEN-LAST:event_profileActionPerformed

    private void addmedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmedMouseEntered
        // TODO add your handling code here:
        
        addmed.setBackground(new Color(56,78,220));
        addmed.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image3\\buy-online (1).png");
    addmed.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (addmed.getWidth() +25);  // Increase width by 20%
    int newHeight = (int) (addmed.getHeight() +25);  // Increase height by 20%

    // Set the bounds for the button manually
    addmed.setBounds(addmed.getX()-10, addmed.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_addmedMouseEntered

    private void addmedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmedMouseExited
        // TODO add your handling code here:
           addmed.setBackground(Color.WHITE);
        addmed.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image3\\buy-online.png");
    addmed.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (addmed.getWidth() -25);  // Increase width by 20%
    int newHeight = (int) (addmed.getHeight() -25);  // Increase height by 20%

    // Set the bounds for the button manually
    addmed.setBounds(addmed.getX()+10, addmed.getY()+10, newWidth, newHeight);
    }//GEN-LAST:event_addmedMouseExited

    private void logout_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "DO you Want logout", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            this.setVisible(false);
            new login().setVisible(true);
        }

    }//GEN-LAST:event_logout_buttonMouseClicked

    private void logout_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseEntered
        // TODO add your handling code here:
        logout_button.setBackground(new Color(56,78,220));
        logout_button.setForeground(Color.WHITE);
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image\\goodbye (2).png");
        logout_button.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (logout_button.getWidth() +25);  // Increase width by 20%
        int newHeight = (int) (logout_button.getHeight() +25);  // Increase height by 20%

        // Set the bounds for the button manually
        logout_button.setBounds(logout_button.getX()-10, logout_button.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_logout_buttonMouseEntered

    private void logout_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseExited
        // TODO add your handling code here:
        // TODO add your handling code here:
        logout_button.setBackground(Color.WHITE);
        logout_button.setForeground(new Color(56,78,220));
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image\\logout (1) (1).png");
        logout_button.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (logout_button.getWidth() -25);  // Increase width by 20%
        int newHeight = (int) (logout_button.getHeight() -25);  // Increase height by 20%

        // Set the bounds for the button manually
        logout_button.setBounds(logout_button.getX()+10, logout_button.getY()+10, newWidth, newHeight);
    }//GEN-LAST:event_logout_buttonMouseExited

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "DO you Want logout", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void exit_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseEntered
        // TODO add your handling code here:
        exit_button.setBackground(new Color(56,78,220));
        exit_button.setForeground(Color.WHITE);
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image\\bye (1).png");
        exit_button.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (exit_button.getWidth() +25);  // Increase width by 20%
        int newHeight = (int) (exit_button.getHeight() +25);  // Increase height by 20%

        // Set the bounds for the button manually
        exit_button.setBounds(exit_button.getX()-10, exit_button.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_exit_buttonMouseEntered

    private void exit_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseExited
        // TODO add your handling code here:
        // TODO add your handling code here:
        exit_button.setBackground(Color.WHITE);
        exit_button.setForeground(new Color(56,78,220));
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image\\switch.png");
        exit_button.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (exit_button.getWidth() -25);  // Increase width by 20%
        int newHeight = (int) (exit_button.getHeight() -25);  // Increase height by 20%

        // Set the bounds for the button manually
        exit_button.setBounds(exit_button.getX()+10, exit_button.getY()+10, newWidth, newHeight);
    }//GEN-LAST:event_exit_buttonMouseExited

    private void viewmedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewmedMouseEntered
        // TODO add your handling code here:
        viewmed.setBackground(new Color(56,78,220));
        viewmed.setForeground(Color.WHITE);
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image3\\list (2).png");
        viewmed.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (viewmed.getWidth() +25);  // Increase width by 20%
        int newHeight = (int) (viewmed.getHeight() +25);  // Increase height by 20%

        // Set the bounds for the button manually
        viewmed.setBounds(viewmed.getX()-10, viewmed.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_viewmedMouseEntered

    private void viewmedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewmedMouseExited
        // TODO add your handling code here:
        viewmed.setBackground(Color.WHITE);
        viewmed.setForeground(new Color(56,78,220));
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image3\\list.png");
        viewmed.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (viewmed.getWidth() -25);  // Increase width by 20%
        int newHeight = (int) (viewmed.getHeight() -25);  // Increase height by 20%

        // Set the bounds for the button manually
        viewmed.setBounds(viewmed.getX()+10, viewmed.getY()+10, newWidth, newHeight);
    }//GEN-LAST:event_viewmedMouseExited

    private void viewmedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewmedMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_viewmedMousePressed

    private void viewmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmedActionPerformed
        // TODO add your handling code here:
           new show_medicine().setVisible(true);//dispose();

    }//GEN-LAST:event_viewmedActionPerformed

    private void updatemedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatemedMouseEntered
        // TODO add your handling code here:
        updatemed.setBackground(new Color(56,78,220));
        updatemed.setForeground(Color.WHITE);
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image3\\edit (1).png");
        updatemed.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (updatemed.getWidth() +25);  // Increase width by 20%
        int newHeight = (int) (updatemed.getHeight() +25);  // Increase height by 20%

        // Set the bounds for the button manually
        updatemed.setBounds(updatemed.getX()-10, updatemed.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_updatemedMouseEntered

    private void updatemedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatemedMouseExited
        // TODO add your handling code here:
        // TODO add your handling code here:
        updatemed.setBackground(Color.WHITE);
        updatemed.setForeground(new Color(56,78,220));
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image3\\edit.png");
        updatemed.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (updatemed.getWidth() -25);  // Increase width by 20%
        int newHeight = (int) (updatemed.getHeight() -25);  // Increase height by 20%

        // Set the bounds for the button manually
        updatemed.setBounds(updatemed.getX()+10, updatemed.getY()+10, newWidth, newHeight);
    }//GEN-LAST:event_updatemedMouseExited

    private void updatemedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemedActionPerformed
        // TODO add your handling code here:
       new UpdateMedicine().setVisible(true);//dispose();

    }//GEN-LAST:event_updatemedActionPerformed

    private void viewbillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbillMouseEntered
        // TODO add your handling code here:
        viewbill.setBackground(new Color(56,78,220));
        viewbill.setForeground(Color.WHITE);
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image3\\prescription (1).png");
        viewbill.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (viewbill.getWidth() +25);  // Increase width by 20%
        int newHeight = (int) (viewbill.getHeight() +25);  // Increase height by 20%

        // Set the bounds for the button manually
        viewbill.setBounds(viewbill.getX()-10, viewbill.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_viewbillMouseEntered

    private void viewbillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbillMouseExited
        // TODO add your handling code here:
        viewbill.setBackground(Color.WHITE);
        viewbill.setForeground(new Color(56,78,220));
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image3\\prescription.png");
        viewbill.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (viewbill.getWidth() -25);  // Increase width by 20%
        int newHeight = (int) (viewbill.getHeight() -25);  // Increase height by 20%

        // Set the bounds for the button manually
        viewbill.setBounds(viewbill.getX()+10, viewbill.getY()+10, newWidth, newHeight);
    }//GEN-LAST:event_viewbillMouseExited

    private void viewbillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbillMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_viewbillMousePressed

    private void viewbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbillActionPerformed
        // TODO add your handling code here:
        new viewBill().setVisible(true);//dispose();

    }//GEN-LAST:event_viewbillActionPerformed

    private void sellmedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellmedMouseClicked
        // TODO add your handling code here:
        //   new user().setVisible(true);
    }//GEN-LAST:event_sellmedMouseClicked

    private void sellmedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellmedMouseEntered
        // TODO add your handling code here:
        sellmed.setBackground(new Color(56,78,220));
        sellmed.setForeground(Color.WHITE);
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image3\\medication (2).png");
        sellmed.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (sellmed.getWidth() +25);  // Increase width by 20%
        int newHeight = (int) (sellmed.getHeight() +25);  // Increase height by 20%

        // Set the bounds for the button manually
        sellmed.setBounds(sellmed.getX()-10, sellmed.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_sellmedMouseEntered

    private void sellmedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellmedMouseExited
        // TODO add your handling code here:
        sellmed.setBackground(Color.WHITE);
        sellmed.setForeground(new Color(56,78,220));
        // Set icon for the button
        ImageIcon icon = new ImageIcon("src\\image3\\medication (1).png");
        sellmed.setIcon(icon);

        // Increase the size of the button
        int newWidth = (int) (sellmed.getWidth() -25);  // Increase width by 20%
        int newHeight = (int) (sellmed.getHeight() -25);  // Increase height by 20%

        // Set the bounds for the button manually
        sellmed.setBounds(sellmed.getX()+10, sellmed.getY()+10, newWidth, newHeight);
    }//GEN-LAST:event_sellmedMouseExited

    private void sellmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellmedActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        //dispose();
        // user hpage=new user();
        // hpage.show();
        new sell_medicine(username).setVisible(true);//dispose();

    }//GEN-LAST:event_sellmedActionPerformed

    private void addmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmedActionPerformed
     // TODO add your handling code here:
       new add_medicine().setVisible(true);//dispose();
    }//GEN-LAST:event_addmedActionPerformed

    private void addmedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmedMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmedMousePressed

    private void profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard("user_name").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmed;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout_button;
    private javax.swing.JLabel name_label;
    private javax.swing.JButton profile;
    private javax.swing.JButton sellmed;
    private javax.swing.JButton updatemed;
    private javax.swing.JButton viewbill;
    private javax.swing.JButton viewmed;
    // End of variables declaration//GEN-END:variables
}
