/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package pharmacy_new;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pharmacy.management.system.Profile;
import pharmacy.management.system.user;
import pharmacy.management.system.viewuser;

/**
 *
 * @author Abdulhalim
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     * @param receive_name
     */
      String usename;
    public Homepage(String receive_name) {
        initComponents();
       usename=receive_name;
        name_label.setText("Welcome Back, "+receive_name);
        this.setTitle("Home page");
        this.setLocation(75, 25);
        this.setSize(1366, 800);
        this.setVisible(true);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
          add_userr.setBackground(Color.WHITE);
        add_userr.setForeground(new Color(56,78,220));
         view_button.setBackground(Color.WHITE);
        view_button.setForeground(new Color(56,78,220));
         update_button.setBackground(Color.WHITE);
        update_button.setForeground(new Color(56,78,220));
         exit_button.setBackground(Color.WHITE);
        exit_button.setForeground(new Color(56,78,220));
          profile_button.setBackground(Color.WHITE);
        profile_button.setForeground(new Color(56,78,220));
          logout_button.setBackground(Color.WHITE);
        logout_button.setForeground(new Color(56,78,220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        profile_button = new javax.swing.JButton();
        add_userr = new javax.swing.JButton();
        view_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        name_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name_label.setForeground(new java.awt.Color(102, 102, 255));
        name_label.setText("Welcome Back!!, Ahmed");
        jPanel1.add(name_label);
        name_label.setBounds(30, 50, 440, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(6, 93, 1448, 10);

        profile_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        profile_button.setForeground(new java.awt.Color(51, 51, 255));
        profile_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user (2).png"))); // NOI18N
        profile_button.setText("Profile");
        profile_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile_button.setFocusable(false);
        profile_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profile_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profile_buttonMouseExited(evt);
            }
        });
        profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(profile_button);
        profile_button.setBounds(760, 150, 370, 140);

        add_userr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add_userr.setForeground(new java.awt.Color(51, 51, 255));
        add_userr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-friend (2).png"))); // NOI18N
        add_userr.setText("Add user");
        add_userr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_userr.setFocusable(false);
        add_userr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_userrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_userrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_userrMouseExited(evt);
            }
        });
        add_userr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_userrActionPerformed(evt);
            }
        });
        jPanel1.add(add_userr);
        add_userr.setBounds(290, 150, 370, 140);

        view_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        view_button.setForeground(new java.awt.Color(51, 51, 255));
        view_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/groups.png"))); // NOI18N
        view_button.setText("View user");
        view_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view_button.setFocusable(false);
        view_button.setIconTextGap(12);
        view_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                view_buttonMousePressed(evt);
            }
        });
        view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(view_button);
        view_button.setBounds(290, 340, 370, 140);

        logout_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout_button.setForeground(new java.awt.Color(51, 51, 255));
        logout_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout (1) (1).png"))); // NOI18N
        logout_button.setText("Log out");
        logout_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_button.setFocusable(false);
        logout_button.setIconTextGap(12);
        logout_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_buttonMouseExited(evt);
            }
        });
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(logout_button);
        logout_button.setBounds(760, 340, 370, 140);

        exit_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exit_button.setForeground(new java.awt.Color(51, 51, 255));
        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/switch.png"))); // NOI18N
        exit_button.setText("Exit");
        exit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_button.setFocusable(false);
        exit_button.setIconTextGap(12);
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_buttonMouseExited(evt);
            }
        });
        jPanel1.add(exit_button);
        exit_button.setBounds(760, 530, 370, 140);

        update_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        update_button.setForeground(new java.awt.Color(51, 51, 255));
        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/teamwork.png"))); // NOI18N
        update_button.setText("Update user");
        update_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_button.setFocusable(false);
        update_button.setIconTextGap(12);
        update_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                update_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                update_buttonMouseExited(evt);
            }
        });
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(update_button);
        update_button.setBounds(290, 530, 370, 140);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Dashboard");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(514, 23, 260, 58);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profile_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseEntered
        // TODO add your handling code here:
         profile_button.setBackground(new Color(56,78,220));
        profile_button.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\profile.png");
    profile_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (profile_button.getWidth() +25);  // Increase width by 20%
    int newHeight = (int) (profile_button.getHeight() +25);  // Increase height by 20%

    // Set the bounds for the button manually
    profile_button.setBounds(profile_button.getX()-10, profile_button.getY()-10, newWidth, newHeight);

    }//GEN-LAST:event_profile_buttonMouseEntered

    private void add_userrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_userrMouseEntered
        // TODO add your handling code here:
        add_userr.setBackground(new Color(56,78,220));
        add_userr.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\add-friend (3).png");
    add_userr.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (add_userr.getWidth() +25);  // Increase width by 20%
    int newHeight = (int) (add_userr.getHeight() +25);  // Increase height by 20%

    // Set the bounds for the button manually
    add_userr.setBounds(add_userr.getX()-10, add_userr.getY()-10, newWidth, newHeight);

    }//GEN-LAST:event_add_userrMouseEntered

    private void add_userrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_userrMouseExited
        // TODO add your handling code here:
         add_userr.setBackground(Color.WHITE);
        add_userr.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\add-friend (2).png");
    add_userr.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (add_userr.getWidth() -25);  // Increase width by 20%
    int newHeight = (int) (add_userr.getHeight() -25);  // Increase height by 20%

    // Set the bounds for the button manually
    add_userr.setBounds(add_userr.getX()+10, add_userr.getY()+10, newWidth, newHeight);

    }//GEN-LAST:event_add_userrMouseExited

    private void add_userrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_userrActionPerformed
         // TODO add your handling code here:
         //this.setVisible(false);
          //dispose();
               // user hpage=new user();
               // hpage.show();
   new user().setVisible(true);//dispose();
   

    }//GEN-LAST:event_add_userrActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void view_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_buttonMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_view_buttonMousePressed

    private void view_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_buttonMouseExited
        // TODO add your handling code here:
           view_button.setBackground(Color.WHITE);
        view_button.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\groups.png");
    view_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (view_button.getWidth() -25);  // Increase width by 20%
    int newHeight = (int) (view_button.getHeight() -25);  // Increase height by 20%

    // Set the bounds for the button manually
    view_button.setBounds(view_button.getX()+10, view_button.getY()+10, newWidth, newHeight);

    }//GEN-LAST:event_view_buttonMouseExited

    private void view_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_buttonMouseEntered
        // TODO add your handling code here:
            view_button.setBackground(new Color(56,78,220));
        view_button.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\groups (2) (1).png");
    view_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (view_button.getWidth() +25);  // Increase width by 20%
    int newHeight = (int) (view_button.getHeight() +25);  // Increase height by 20%

    // Set the bounds for the button manually
    view_button.setBounds(view_button.getX()-10, view_button.getY()-10, newWidth, newHeight);

    }//GEN-LAST:event_view_buttonMouseEntered

    private void update_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_buttonMouseEntered
        // TODO add your handling code here:
           update_button.setBackground(new Color(56,78,220));
        update_button.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\teamwork (1).png");
    update_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (update_button.getWidth() +25);  // Increase width by 20%
    int newHeight = (int) (update_button.getHeight() +25);  // Increase height by 20%

    // Set the bounds for the button manually
    update_button.setBounds(update_button.getX()-10, update_button.getY()-10, newWidth, newHeight);

    }//GEN-LAST:event_update_buttonMouseEntered

    private void logout_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseEntered
        // TODO add your handling code here:
           logout_button.setBackground(new Color(56,78,220));
        logout_button.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\goodbye (2).png");
    logout_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (logout_button.getWidth() +25);  // Increase width by 20%
    int newHeight = (int) (logout_button.getHeight() +25);  // Increase height by 20%

    // Set the bounds for the button manually
    logout_button.setBounds(logout_button.getX()-10, logout_button.getY()-10, newWidth, newHeight);

    }//GEN-LAST:event_logout_buttonMouseEntered

    private void exit_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseEntered
        // TODO add your handling code here:
           exit_button.setBackground(new Color(56,78,220));
        exit_button.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\bye (1).png");
    exit_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (exit_button.getWidth() +25);  // Increase width by 20%
    int newHeight = (int) (exit_button.getHeight() +25);  // Increase height by 20%

    // Set the bounds for the button manually
    exit_button.setBounds(exit_button.getX()-10, exit_button.getY()-10, newWidth, newHeight);

    }//GEN-LAST:event_exit_buttonMouseEntered

    private void exit_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseExited
        // TODO add your handling code here:
          // TODO add your handling code here:
           exit_button.setBackground(Color.WHITE);
        exit_button.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\switch.png");
    exit_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (exit_button.getWidth() -25);  // Increase width by 20%
    int newHeight = (int) (exit_button.getHeight() -25);  // Increase height by 20%

    // Set the bounds for the button manually
    exit_button.setBounds(exit_button.getX()+10, exit_button.getY()+10, newWidth, newHeight);

    }//GEN-LAST:event_exit_buttonMouseExited

    private void update_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_buttonMouseExited
        // TODO add your handling code here:
          // TODO add your handling code here:
           update_button.setBackground(Color.WHITE);
        update_button.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\teamwork.png");
    update_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (update_button.getWidth() -25);  // Increase width by 20%
    int newHeight = (int) (update_button.getHeight() -25);  // Increase height by 20%

    // Set the bounds for the button manually
    update_button.setBounds(update_button.getX()+10, update_button.getY()+10, newWidth, newHeight);

    }//GEN-LAST:event_update_buttonMouseExited

    private void profile_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_buttonMouseExited
        // TODO add your handling code here:
          // TODO add your handling code here:
           profile_button.setBackground(Color.WHITE);
        profile_button.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\user (2).png");
    profile_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (profile_button.getWidth() -25);  // Increase width by 20%
    int newHeight = (int) (profile_button.getHeight() -25);  // Increase height by 20%

    // Set the bounds for the button manually
    profile_button.setBounds(profile_button.getX()+10, profile_button.getY()+10, newWidth, newHeight);

    }//GEN-LAST:event_profile_buttonMouseExited

    private void logout_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseExited
        // TODO add your handling code here:
          // TODO add your handling code here:
           logout_button.setBackground(Color.WHITE);
        logout_button.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image\\logout (1) (1).png");
    logout_button.setIcon(icon);

    // Increase the size of the button
    int newWidth = (int) (logout_button.getWidth() -25);  // Increase width by 20%
    int newHeight = (int) (logout_button.getHeight() -25);  // Increase height by 20%

    // Set the bounds for the button manually
    logout_button.setBounds(logout_button.getX()+10, logout_button.getY()+10, newWidth, newHeight);

    }//GEN-LAST:event_logout_buttonMouseExited

    private void logout_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "DO you Want logout", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
        this.setVisible(false);
        new login().setVisible(true);
        }
        
    }//GEN-LAST:event_logout_buttonMouseClicked

    private void exit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMouseClicked
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null, "DO you Want logout", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_exit_buttonMouseClicked

    private void add_userrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_userrMouseClicked
        // TODO add your handling code here:
     //   new user().setVisible(true);
    }//GEN-LAST:event_add_userrMouseClicked

    private void profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_buttonActionPerformed
        // TODO add your handling code here:
        new Profile(usename).setVisible(true);//dispose();
    }//GEN-LAST:event_profile_buttonActionPerformed

    private void view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_buttonActionPerformed
        // TODO add your handling code here:
        new viewuser(usename).setVisible(true);//dispose();
        
    }//GEN-LAST:event_view_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
      new PharmacyManagementSystem().setVisible(true);//dispose();
        
    }//GEN-LAST:event_update_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage("user").setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_userr;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout_button;
    private javax.swing.JLabel name_label;
    private javax.swing.JButton profile_button;
    private javax.swing.JButton update_button;
    private javax.swing.JButton view_button;
    // End of variables declaration//GEN-END:variables
}
