/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package pharmacy_new;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Abdulhalim
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
   Connection con;
    ImageIcon newIcon = new ImageIcon("src\\image\\Eye 4.png");
    ImageIcon newIcon2 = new ImageIcon("src\\image\\Invisible 4.png");

     int i=0;
    public login() {
        initComponents();
        this.setTitle("Login");
        this.setLocation(250, 100);
        //for_test.setIcon(iicon);
        for_test.setIcon(new ImageIcon("src\\image\\accept (3).png"));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "abdo", "abdo1234");
        } catch (Exception e) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, e);
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pass_text = new javax.swing.JPasswordField();
        eye = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        for_test = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Blue Gradient Modern Simple Pharmacy Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(56, 78, 220));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User name");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(39, 139, 84, 19);

        jLabel3.setBackground(new java.awt.Color(51, 51, 255));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(220, 30, 67, 32);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(39, 228, 84, 19);

        jLabel5.setBackground(new java.awt.Color(56, 78, 220));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("________________________________________________");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLabel5.setFocusable(false);
        jPanel4.add(jLabel5);
        jLabel5.setBounds(40, 170, 328, 29);

        user_text.setBackground(new java.awt.Color(56, 78, 220));
        user_text.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        user_text.setForeground(new java.awt.Color(255, 255, 255));
        user_text.setBorder(null);
        user_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_textActionPerformed(evt);
            }
        });
        jPanel4.add(user_text);
        user_text.setBounds(39, 160, 304, 25);

        jLabel6.setBackground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("________________________________________________");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel6.setFocusable(false);
        jPanel4.add(jLabel6);
        jLabel6.setBounds(1301, 591, 328, 29);

        jButton1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("LOGIN");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(80, 390, 286, 50);

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hello! Let's Get Started");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(180, 60, 168, 28);

        jLabel7.setBackground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("________________________________________________");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel7.setFocusable(false);
        jPanel4.add(jLabel7);
        jLabel7.setBounds(2925, 386, 328, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("-----------------------------------------------------------------------------");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 280, 370, 16);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User 2.png"))); // NOI18N
        jPanel4.add(jLabel11);
        jLabel11.setBounds(390, 160, 30, 40);

        pass_text.setBackground(new java.awt.Color(56, 78, 220));
        pass_text.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        pass_text.setForeground(new java.awt.Color(255, 255, 255));
        pass_text.setBorder(null);
        pass_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_textActionPerformed(evt);
            }
        });
        jPanel4.add(pass_text);
        pass_text.setBounds(39, 253, 304, 31);

        eye.setBackground(new java.awt.Color(56, 78, 220));
        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Invisible 4.png"))); // NOI18N
        eye.setBorder(null);
        eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eyeMouseEntered(evt);
            }
        });
        eye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeActionPerformed(evt);
            }
        });
        jPanel4.add(eye);
        eye.setBounds(390, 250, 40, 30);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Forget Password ?");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(280, 300, 126, 28);
        jPanel4.add(for_test);
        for_test.setBounds(80, 70, 37, 0);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 490, 479);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            //   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/company", "root", "root");
            String username=user_text.getText();
            String pas=pass_text.getText();

            String log="select * from appuser where username='"+username+"' and password='"+pas+"'";
            PreparedStatement stmt=con.prepareStatement(log);
            ResultSet rs=stmt.executeQuery();
            if(rs.next()){
                String role=rs.getString("userRole");
                if(role.equals("Admin"))
                {
                     dispose();
                Homepage hpage=new Homepage(username);
                hpage.show();
                }
                else
                {
                  dispose();
                dashboard hpage=new dashboard(username);
                hpage.show();
                }
                 

            }else{
                JOptionPane.showMessageDialog(this, "username or password is wrong");
                pass_text.setText("");
                user_text.setText("");
            }

        } catch (SQLException ex) {
            System.out.println("Error");
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void user_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_textActionPerformed

    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked
       if(i%2==0){
        pass_text.setEchoChar((char)0);
        //pass_text.setVisible(true);
        //  pass_text.setEnabled(true);
        eye.setIcon(newIcon);
       }else{
       eye.setIcon(newIcon2);
       pass_text.setEchoChar((char)8226);
        //pass_text.setVisible(false);
       // pass_text.setEnabled(false);
      
       
       }
       i++;
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeMouseClicked

    private void eyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pass_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_textActionPerformed

    private void eyeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eye;
    private javax.swing.JLabel for_test;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField pass_text;
    private javax.swing.JTextField user_text;
    // End of variables declaration//GEN-END:variables
}
