/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.management.system;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Date;
/**
 *
 * @author Elasad
 */
public class user extends javax.swing.JFrame {
    public String emailpattern="^[a-zA-z0-9]+[@]+[a-zA-z0-9]+[.]+[a-zA-z0-9]+$";
    public String mobilenumberpattern="^[0-9]*$";
    public int checkusername=0;

    

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        iconlabel.setVisible(false);
            save.setBackground(Color.WHITE);
        save.setForeground(new Color(56,78,220));
        this.setLocationRelativeTo(null);
        set();
    }

    public void set(){
    txtname.setText("");
   txtmobilenumber.setText("");
txtemail.setText("");
txtpassword.setText("");
txtusername.setText("");
txtaddress.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      public String getUniqueId(String p){
    return p+System.nanoTime();
    }
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        combouserRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateDOB = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtmobilenumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        iconlabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 78, 220));
        jLabel1.setText("Add user");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 78, 220));
        jLabel2.setText("User Role");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        combouserRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combouserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist" }));
        getContentPane().add(combouserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 300, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 78, 220));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 188, 37, -1));

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(56, 78, 220));
        jLabel4.setText("DOB (Date Of Birth)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 130, -1));

        dateDOB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(56, 78, 220));
        jLabel5.setText("Mobile Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 100, -1));

        txtmobilenumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtmobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(56, 78, 220));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 37, -1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 300, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(56, 78, 220));
        jLabel7.setText("Username");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, 20));

        txtusername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusernameKeyReleased(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 300, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(56, 78, 220));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 60, -1));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 300, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(56, 78, 220));
        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 348, 60, -1));

        txtaddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 300, -1));

        save.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image2/save.png"))); // NOI18N
        save.setText("Save");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 110, -1));
        getContentPane().add(iconlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Close Window.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 20, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image2/back.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyReleased
        String username=txtusername.getText();
        if(username.equals("")){
            iconlabel.setVisible(true);
            iconlabel.setIcon(new ImageIcon("src\\image2\\yes.png"));
            iconlabel.setText("");
            checkusername=0;
            
           try{
             Connection  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "abdo", "abdo1234");
             Statement st=con.createStatement();
             ResultSet rs=st.executeQuery("select *from appuser where username =\"+username+\"");
             while(rs.next()){
                 checkusername=1;
                 iconlabel.setIcon(new ImageIcon("src\\image\\no.png"));
                  iconlabel.setText("");
             }
           }
               catch(Exception ex){
               JOptionPane.showMessageDialog(null,ex);
                   
           } 
          
        }
        else{
            iconlabel.setVisible(false);
        }
    }//GEN-LAST:event_txtusernameKeyReleased

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String userRole=(String)combouserRole.getSelectedItem();
        String name=txtname.getText();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=dateDOB.getDate();
        String dop="";
        if(date!=null){
            dop=dFormat.format(dateDOB.getDate());
        }
        String mobilenumber=txtmobilenumber.getText();
        String email=txtemail.getText();
        String password=txtpassword.getText();
        String username=txtusername.getText();
        String address=txtaddress.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required.");
        }else if(dop.equals("")){
            JOptionPane.showMessageDialog(null,"Date of birth is required.");
        }else if(mobilenumber.equals("")){
            JOptionPane.showMessageDialog(null,"Mobile number faield is required.");
        }else if(!mobilenumber.matches(mobilenumberpattern)||mobilenumber.length()!=11){
            JOptionPane.showMessageDialog(null,"Mobile number faield is invalid.");
        }else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Email field is required.");
        }else if(!email.matches(emailpattern)){
            JOptionPane.showMessageDialog(null,"Email field is invalid.");
        }else if(username.equals("")){
            JOptionPane.showMessageDialog(null,"Username field is required.");
        }else if(checkusername==1){
            JOptionPane.showMessageDialog(null,"Username is already exist.");
        }else if(password.equals("")){
            JOptionPane.showMessageDialog(null,"Password field is required.");
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(null,"Address field is required.");
        }else{
            try{
                 Connection  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "abdo", "abdo1234");
                  PreparedStatement ps=con.prepareStatement("insert into appuser(userRole,name,dob,mobilenumber,email,password,username,address,appuser_pk) values(?,?,?,?,?,?,?,?,?)");
                  ps.setString(1, userRole);
                  ps.setString(2, name);
                  ps.setString(3, dop);
                  ps.setString(4, mobilenumber);
                  ps.setString(5, email);
                  ps.setString(6, password);
                  ps.setString(7, username);
                  ps.setString(8, address);
                  ps.setString(9, getUniqueId(mobilenumber.substring(0, 4)));
                  ps.executeUpdate();
                   JOptionPane.showMessageDialog(null,"User Added Successfully.");
                   setVisible(false);
                   new user().setVisible(true);
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        // TODO add your handling code here:
       save.setBackground(new Color(56,78,220));
        save.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image2\\save.png");
    save.setIcon(icon);

    // Increase the size of the button
   // int newWidth = (int) (save.getWidth() +25);  // Increase width by 20%
   // int newHeight = (int) (save.getHeight() +25);  // Increase height by 20%

    // Set the bounds for the button manually
   // save.setBounds(save.getX()-10, save.getY()-10, newWidth, newHeight);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        // TODO add your handling code here:
         save.setBackground(Color.WHITE);
        save.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image2\\save.png");
    save.setIcon(icon);

    // Increase the size of the button
    //int newWidth = (int) (save.getWidth()-25 );  // Increase width by 20%
    //int newHeight = (int) (save.getHeight()-25 );  // Increase height by 20%

    // Set the bounds for the button manually
   // save.setBounds(save.getX()+10, save.getY()+10, newWidth, newHeight);
    }//GEN-LAST:event_saveMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combouserRole;
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.JLabel iconlabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton save;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobilenumber;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

    private void setVisibale(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
